from lsst.obs.base import FilterDefinition, FilterDefinitionCollection

# lambdaMin and lambda max are chosen to be where the filter rises above 1%
# from HELP/SVO:
#https://github.com/H-E-L-P/herschelhelp_python/blob/master/database_builder/filters/
VISTA_FILTER_DEFINITIONS = FilterDefinitionCollection(
    FilterDefinition(band="Clear", physical_filter="NONE", lambdaEff=0,
                     alias=["Clear","NONE", "None", "Unrecognised", "UNRECOGNISED",
                            "Unrecognized", "UNRECOGNIZED", "NOTSET"]),
    FilterDefinition(physical_filter="VISTA-Z",
                     band="z",
                     afw_name='z2',
                     lambdaEff=8762.4437058376, 
                     lambdaMin=8156.5423076923, 
                     lambdaMax=9400.45),
    FilterDefinition(physical_filter="VISTA-Y",
                     band="y",
                     afw_name='y2',
                     lambdaEff=10184.228370757, 
                     lambdaMin=9427.060857538, 
                     lambdaMax=10976.565495208),
    FilterDefinition(physical_filter="VISTA-J",
                     band="j",
                     lambdaEff=12464.429377059, 
                     lambdaMin=11427.444047011, 
                     lambdaMax=13759.028571429),
    FilterDefinition(physical_filter="VISTA-H",
                     band="h",
                     lambdaEff=16310.014908445, 
                     lambdaMin=14603.599766628, 
                     lambdaMax=18422.112893276),
    FilterDefinition(physical_filter="VISTA-Ks",
                     band="ks",
                     lambdaEff=21336.637909756, 
                     lambdaMin=19332.653810836, 
                     lambdaMax=23674.330024814),
    #Copy pasted from obs_suabru. Can I replace with an import?
    FilterDefinition(physical_filter="HSC-G",
                     band="g",
                     lambdaEff=477, alias={'W-S-G+'}),
    FilterDefinition(physical_filter="HSC-R",
                     band="r",
                     lambdaEff=623, alias={'W-S-R+'}),
    FilterDefinition(physical_filter="HSC-I",
                     band="i",
                     lambdaEff=775, alias={'W-S-I+'}),
    FilterDefinition(physical_filter="HSC-Z",
                     band="z",
                     lambdaEff=925, alias={'W-S-Z+'}),
    FilterDefinition(physical_filter="HSC-Y",
                     band="y",
                     lambdaEff=990, alias={'W-S-ZR'}),
)